---
name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - ironwolphern
body:
  - type: input
    id: contact-name
    attributes:
      label: Contact Name
      description: What is your name?
      placeholder: ex. John Doe
    validations:
      required: false
  - type: input
    id: contact-email
    attributes:
      label: Contact Email
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
      value: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
      placeholder: I would like [...]
      value: I would like [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've considered [...]
      value: I've considered [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
      placeholder: Other context or screenshots.
      value: Other context or screenshots.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue,
        you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
